name: Node.js CI

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm ci

    - name: Run index.js
      run: node index.js

    - name: Update README
      run: |
        git config --global user.email "igor.k.nsk@gmail.com"
        git config --global user.name "igorgmail"
        git add README.md
        git commit -am "bot: updated README.md"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
